// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vkumqdntyecpmilulynm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZrdW1xZG50eWVjcG1pbHVseW5tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxNzI5OTQsImV4cCI6MjA2MTc0ODk5NH0.MNWUhEx_TLoKU5tTzBg52W6M3nd4JR-QLFs6ECpvZ3U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);